name: ETF Guardian Daily

on:

  workflow_dispatch:

  schedule:
    - cron: '30 8 * * 1-5'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5

      with:

        python-version: "3.12"

    - run: pip install -r requirements.txt

    - run: python scripts/main.py

    - name: Commit Report

      run: |

        git config user.name github-actions

        git config user.email github-actions@github.com

        git add reports/

        git commit -m "Daily Report"

        git push
